### ISSUE TITLE
NPE when calling create dataset with a subset of properties

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/data-sets#23]
The implementation of the ZosmfCreateRequest class relies on all request parameters to be present (DataSetCreateRequest class)  
If not the NPE at the bottom is generated in the Spring Boot log and the response to the client is an HTTP 500.
This is the sample I used
{
"name": "user.test.jcd","recordLength":80,"recordFormat":"FB"
}
java.lang.NullPointerException: null
        at org.zowe.data.sets.model.ZosmfCreateRequest.createFromDataSetCreateRequest(ZosmfCreateRequest.java:45) ~[data-sets-model-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
        at org.zowe.data.sets.services.ZosmfDataSetService.convertIntoZosmfRequestJson(ZosmfDataSetService.java:279) ~[classes!/:0.0.1-SNAPSHOT]
        at org.zowe.data.sets.services.ZosmfDataSetService.createDataSet(ZosmfDataSetService.java:244) ~[classes!/:0.0.1-SNAPSHOT]

**Comment by Colin-Stone** [comment]
This may be relevant https://projectlombok.org/features/NonNull
